In [1]:
import numpy as np

In [2]:
nn = np.array([[3,4,4],[4,5,6]])
nn

array([[3, 4, 4],
       [4, 5, 6]])

In [5]:
nn.shape


(2, 3)

In [15]:
nnp = np.array([[1,2,3,4,5],[3,4,5,6,66],[3,4,5,4,5]])
nnp.shape

(3, 5)

In [16]:
nnp.shape=(5,3)
nnp

array([[ 1,  2,  3],
       [ 4,  5,  3],
       [ 4,  5,  6],
       [66,  3,  4],
       [ 5,  4,  5]])

In [17]:
nnp.shape

(5, 3)

In [23]:
nnp.shape =(3,5)
nnp

array([[ 1,  2,  3,  4,  5],
       [ 3,  4,  5,  6, 66],
       [ 3,  4,  5,  4,  5]])

In [24]:
nc = np.array([3,4,5,5])
nb = np.array([3,4,5,6])
print(np.vstack((nc,nb)))

[[3 4 5 5]
 [3 4 5 6]]


In [25]:
nc = np.array([3,4,7,5])
nb = np.array([3,4,5,6])
print(np.hstack((nc,nb)))

[3 4 5 5 3 4 5 6]


In [27]:
n555 = np.array([2,3,4,5,5])
n554=np.array([2,3,4,5,6])
cc = np.column_stack((n555,n554))
cc

array([[2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [5, 6]])

In [28]:
print(np.column_stack((nc,nb)))

[[3 3]
 [4 4]
 [5 5]
 [5 6]]


In [34]:
c = np.intersect1d(nc,nb)
c

array([3, 4, 5])

In [32]:
c = np.setdiff1d(nc,nb)
c

array([], dtype=int32)

In [31]:
n = np.array([34,43])
n2=np.array([44,44])
c = np.sum((n,n2))
c

165

In [35]:
cb = np.array([3,4])
bb = np.array([3,6])
c = np.sum((cb,bb),axis=0)
c

array([ 6, 10])

In [36]:
bb+34
bb

array([3, 6])

In [37]:
const = bb/4
const

array([0.75, 1.5 ])

In [39]:
const = bb*5
const

array([15, 30])