In [1]:
import numpy as np

In [5]:
print(np.array([1,2,3,4,5,6]))


[1 2 3 4 5 6]


In [6]:
n2 = np.array([[1,2,3,4,5,6,7]])

In [7]:
print(n2)

[[1 2 3 4 5 6 7]]


In [9]:
n5=np.array([[2,3,4,5,6],[1,2,3,4,5]])

In [10]:
print(n5)

[[2 3 4 5 6]
 [1 2 3 4 5]]


In [11]:
type(n5)

numpy.ndarray

In [12]:
# zeros
nn = np.zeros((5,2))
print(nn)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [13]:
nn3 = np.zeros((44,26))
print(nn3)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
# import numpy as np
# np.array([3,4,5])
# np.array([[2,3,4],[3,4,5]])
# np.zeros((5,3))
# np.full((3,4),33)
# np.arange(1,55)
# np.arange(1,10,2)
# np.random.randint(1,44,3)


In [14]:
np3 = np.full((5,2),6)

In [15]:
print(np3)

[[6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]]


In [16]:
nll = np.arange(1,10,2)
print(nll)

[1 3 5 7 9]


In [21]:
sa = np.arange(3,66,3)
print(sa)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63]


In [25]:
ns = np.random.randint(1,33)
print(ns)

29


In [26]:
nos4 = np.random.randint(1,44,6)

In [27]:
print(nos4)

[36 23 14 13 38 16]


In [ ]:
# import numpy as np
# np.array([3,4,5])
# np.array([[2,3,4],[3,4,5]])
# np.zeros((5,3))
# np.full((3,4),33)
# np.arange(1,55)
# np.arange(1,10,2)
# np.random.randint(1,44,3)
# nparray.shape = (3,5) 

In [ ]:
import numpy as np

In [5]:
nu = np.array([[1,2,3,4,5],[3,4,5,6,66],[3,4,5,4,5]])
nu.shape =(3,4)


NameError: name 'np' is not defined

In [6]:
print(np.zeros((2,4)))

NameError: name 'np' is not defined